version: "2"
services:
  podcasts-server:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - webserver

networks:
  webserver:
      external: true
